export const Images = {
  loginBanner: require('./login-banner.png'),
  googleLogo: require('./google-logo.png'),
  emptyFeed: require('./empty-feed.png'),
  emptyLike: require('./empty-likes.png'),
  upload: require('./upload.png'),
  emptyConnection: require('./empty-connections.png'),
  searchUser: require('./search-users.png'),
  zalo: require('./zalo.png'),
  emptyBlocklist: require('./empty-blocklist.png'),
  emptyMessage: require('./empty-messages.png'),
  logo: require('./logo.png'),
  ntqLogo: require('./ntq-logo.png'),
  ntqLogoBlue: require('./ntq-logo-blue.png'),
};
