export enum AppRoutes {
  APP = 'App',
  AUTH = 'Auth',
  BOOT_SCREEN = 'BootScreen',
  LOGIN = 'Login',
  SETTING = 'Setting',
  HOME = 'Home',
  TINDER_NAVIGATOR = 'TinderNavigator',
  TINDER_APP = 'TinderApp',
  TINDER_PROFILE = 'TinderProfile',
  TINDER_MESSAGE = 'TinderMessages',
  TINDER_CONVERSATION = 'TinderConversation',
  MAIN_TAB = 'MainTab',
  HOME_TAB = 'HomeTab',
  NOTIFICATION_TAB = 'NotificationTab',
  PROFILE_TAB = 'ProfileTab',

  MESSAGE_SCREEN = 'MessageScreen',
  CONVERSATION_SCREEN = 'ConversationScreen',
  PROFILE_VIEW_SCREEN = 'ProfileViewScreen',
  POST_VIEW_SCREEN = 'PostViewScreen',
  NOTIFICATION_VIEW_SCREEN = 'NotificationViewScreen',
  LIVE_STREAM_VIEW_SCREEN = 'LiveStreamViewScreen',
  UPDATE_DEPARTMENT_INFO = 'UpdateDepartmentInfo',
  UPDATE_POSITION_INFO = 'UpdatePositionInfo',
  WELCOME_SCREEN = 'WelcomeScreen',
  SEARCH_SCREEN = 'SearchScreen',
  CREATE_POST = 'CreatePost',
  DETAIL_POST = 'DetailPost',
}
