export enum AppRoutes {
  APP = 'App',
  AUTH = 'Auth',
  BOOT_SCREEN = 'BootScreen',
  LOGIN = 'Login',
  SETTING = 'Setting',
  HOME = 'Home',

  MAIN_TAB = 'MainTab',
  HOME_TAB = 'HomeTab',
  EXPLORE_TAB = 'ExploreTab',
  UPLOAD_STACK = 'UploadStack',
  UPLOAD_TAB = 'UploadTab',
  FILTER_SCREEN = 'FilterScreen',
  CAPTION_SCREEN = 'CaptionScreen',
  EDIT_CATION_SCREEN = 'EditCaptionScreen',
  NOTIFICATION_TAB = 'NotificationTab',
  REQUEST_FOLLOW = 'RequestFollow',
  PROFILE_TAB = 'ProfileTab',

  MESSAGE_SCREEN = 'MessageScreen',
  CONVERSATION_SCREEN = 'ConversationScreen',
  PROFILE_VIEW_SCREEN = 'ProfileViewScreen',
  POST_VIEW_SCREEN = 'PostViewScreen',
  NOTIFICATION_VIEW_SCREEN = 'NotificationViewScreen',
  LIVE_STREAM_VIEW_SCREEN = 'LiveStreamViewScreen',
  UPDATE_DEPARTMENT_INFO = 'UpdateDepartmentInfo',
  UPDATE_POSITION_INFO = 'UpdatePositionInfo',
}
